<a href="https://colab.research.google.com/github/Alton1998/University-Notes/blob/main/Question_1_2D_Separable_Fourier_Transform_Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [81]:
import numpy as np
from scipy.fft import rfft,fft

# Part 1

In [82]:
original_mat = [[22,25,35,30],[30,32,33,36],[32,30,36,45],[38,35,32,40]]

In [83]:
original_mat_np_arr= np.array(original_mat)

In [84]:
original_mat_np_arr

array([[22, 25, 35, 30],
       [30, 32, 33, 36],
       [32, 30, 36, 45],
       [38, 35, 32, 40]])

In [85]:
row_transform = []
for row in original_mat_np_arr:
  row_transform.append(fft(row))

In [86]:
row_transform = np.array(row_transform)

In [87]:
row_transform

array([[112. -0.j, -13. +5.j,   2. -0.j, -13. -5.j],
       [131. -0.j,  -3. +4.j,  -5. -0.j,  -3. -4.j],
       [143. -0.j,  -4.+15.j,  -7. -0.j,  -4.-15.j],
       [145. -0.j,   6. +5.j,  -5. -0.j,   6. -5.j]])

In [88]:
column_transform = []
for row in row_transform.transpose():
  column_transform.append((fft(row)))

In [89]:
column_transform = np.array(column_transform)

In [90]:
column_transform = column_transform.transpose()

In [91]:
column_transform

array([[531. -0.j, -14.+29.j, -15. -0.j, -14.-29.j],
       [-31.+14.j, -10. -1.j,   9. +0.j,  -8.+19.j],
       [-21. +0.j, -20.+11.j,   5. +0.j, -20.-11.j],
       [-31.-14.j,  -8.-19.j,   9. +0.j, -10. +1.j]])

# Part 3

In [92]:
squared_orginal_matrix = np.square(original_mat_np_arr)

In [93]:
squared_orginal_matrix

array([[ 484,  625, 1225,  900],
       [ 900, 1024, 1089, 1296],
       [1024,  900, 1296, 2025],
       [1444, 1225, 1024, 1600]])

In [94]:
squared_orginal_matrix_sum = squared_orginal_matrix.sum()

In [95]:
squared_orginal_matrix_sum

18081

In [96]:
scaled_column_transform = (1/4) * column_transform

In [97]:
scaled_column_transform

array([[132.75+0.j  ,  -3.5 +7.25j,  -3.75-0.j  ,  -3.5 -7.25j],
       [ -7.75+3.5j ,  -2.5 -0.25j,   2.25+0.j  ,  -2.  +4.75j],
       [ -5.25+0.j  ,  -5.  +2.75j,   1.25+0.j  ,  -5.  -2.75j],
       [ -7.75-3.5j ,  -2.  -4.75j,   2.25+0.j  ,  -2.5 +0.25j]])

In [98]:
scaled_column_transform_abs = np.abs(scaled_column_transform)

In [99]:
scaled_column_transform_abs

array([[132.75      ,   8.05062109,   3.75      ,   8.05062109],
       [  8.50367568,   2.51246891,   2.25      ,   5.15388203],
       [  5.25      ,   5.70635611,   1.25      ,   5.70635611],
       [  8.50367568,   5.15388203,   2.25      ,   2.51246891]])

In [100]:
scaled_column_transform_square = np.square(scaled_column_transform_abs)

In [101]:
scaled_column_transform_square.sum()

18081.0

# DC Energy Calculation

## Energy in the Signal Domain

In [102]:
signal_energy = np.sum(np.square(np.abs(original_mat_np_arr)))

In [103]:
signal_energy

18081

## Energy in the Frequency Domain

In [104]:
n_rows,n_columns=column_transform.shape

In [105]:
n_rows

4

In [106]:
n_columns

4

In [107]:
frequency_domain_energy = (1/n_rows)*(1/n_columns)*np.sum(np.square(np.abs(column_transform)))

In [108]:
frequency_domain_energy

18081.0

In [111]:
energy_dc_coeff = (1/n_rows)*(1/n_columns)*np.square(np.abs(column_transform[0][0]))

In [112]:
energy_dc_coeff

17622.5625

In [113]:
ratio = energy_dc_coeff/frequency_domain_energy

In [114]:
ratio

0.9746453459432554